/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    media: Media;
    users: User;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    homepage: Homepage;
    about: About;
    'projects-page': ProjectsPage;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'projects-page': ProjectsPageSelect<false> | ProjectsPageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'projects';
                  value: number | Project;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout?: (CallToActionBlock | ContentBlock | MediaBlock | FormBlock)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Brand or client name shown on the case study card.
   */
  client?: string | null;
  excerpt: string;
  /**
   * Add project images and mark one as featured for cards and the project page hero.
   */
  images?:
    | {
        image: number | Media;
        /**
         * Only one image can be featured at a time.
         */
        isFeatured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultTimezone?:
              | (
                  | 'Africa/Abidjan'
                  | 'Africa/Accra'
                  | 'Africa/Addis_Ababa'
                  | 'Africa/Algiers'
                  | 'Africa/Asmera'
                  | 'Africa/Bamako'
                  | 'Africa/Bangui'
                  | 'Africa/Banjul'
                  | 'Africa/Bissau'
                  | 'Africa/Blantyre'
                  | 'Africa/Brazzaville'
                  | 'Africa/Bujumbura'
                  | 'Africa/Cairo'
                  | 'Africa/Casablanca'
                  | 'Africa/Ceuta'
                  | 'Africa/Conakry'
                  | 'Africa/Dakar'
                  | 'Africa/Dar_es_Salaam'
                  | 'Africa/Djibouti'
                  | 'Africa/Douala'
                  | 'Africa/El_Aaiun'
                  | 'Africa/Freetown'
                  | 'Africa/Gaborone'
                  | 'Africa/Harare'
                  | 'Africa/Johannesburg'
                  | 'Africa/Juba'
                  | 'Africa/Kampala'
                  | 'Africa/Khartoum'
                  | 'Africa/Kigali'
                  | 'Africa/Kinshasa'
                  | 'Africa/Lagos'
                  | 'Africa/Libreville'
                  | 'Africa/Lome'
                  | 'Africa/Luanda'
                  | 'Africa/Lubumbashi'
                  | 'Africa/Lusaka'
                  | 'Africa/Malabo'
                  | 'Africa/Maputo'
                  | 'Africa/Maseru'
                  | 'Africa/Mbabane'
                  | 'Africa/Mogadishu'
                  | 'Africa/Monrovia'
                  | 'Africa/Nairobi'
                  | 'Africa/Ndjamena'
                  | 'Africa/Niamey'
                  | 'Africa/Nouakchott'
                  | 'Africa/Ouagadougou'
                  | 'Africa/Porto-Novo'
                  | 'Africa/Sao_Tome'
                  | 'Africa/Tripoli'
                  | 'Africa/Tunis'
                  | 'Africa/Windhoek'
                  | 'America/Adak'
                  | 'America/Anchorage'
                  | 'America/Anguilla'
                  | 'America/Antigua'
                  | 'America/Araguaina'
                  | 'America/Argentina/La_Rioja'
                  | 'America/Argentina/Rio_Gallegos'
                  | 'America/Argentina/Salta'
                  | 'America/Argentina/San_Juan'
                  | 'America/Argentina/San_Luis'
                  | 'America/Argentina/Tucuman'
                  | 'America/Argentina/Ushuaia'
                  | 'America/Aruba'
                  | 'America/Asuncion'
                  | 'America/Bahia'
                  | 'America/Bahia_Banderas'
                  | 'America/Barbados'
                  | 'America/Belem'
                  | 'America/Belize'
                  | 'America/Blanc-Sablon'
                  | 'America/Boa_Vista'
                  | 'America/Bogota'
                  | 'America/Boise'
                  | 'America/Buenos_Aires'
                  | 'America/Cambridge_Bay'
                  | 'America/Campo_Grande'
                  | 'America/Cancun'
                  | 'America/Caracas'
                  | 'America/Catamarca'
                  | 'America/Cayenne'
                  | 'America/Cayman'
                  | 'America/Chicago'
                  | 'America/Chihuahua'
                  | 'America/Ciudad_Juarez'
                  | 'America/Coral_Harbour'
                  | 'America/Cordoba'
                  | 'America/Costa_Rica'
                  | 'America/Coyhaique'
                  | 'America/Creston'
                  | 'America/Cuiaba'
                  | 'America/Curacao'
                  | 'America/Danmarkshavn'
                  | 'America/Dawson'
                  | 'America/Dawson_Creek'
                  | 'America/Denver'
                  | 'America/Detroit'
                  | 'America/Dominica'
                  | 'America/Edmonton'
                  | 'America/Eirunepe'
                  | 'America/El_Salvador'
                  | 'America/Fort_Nelson'
                  | 'America/Fortaleza'
                  | 'America/Glace_Bay'
                  | 'America/Godthab'
                  | 'America/Goose_Bay'
                  | 'America/Grand_Turk'
                  | 'America/Grenada'
                  | 'America/Guadeloupe'
                  | 'America/Guatemala'
                  | 'America/Guayaquil'
                  | 'America/Guyana'
                  | 'America/Halifax'
                  | 'America/Havana'
                  | 'America/Hermosillo'
                  | 'America/Indiana/Knox'
                  | 'America/Indiana/Marengo'
                  | 'America/Indiana/Petersburg'
                  | 'America/Indiana/Tell_City'
                  | 'America/Indiana/Vevay'
                  | 'America/Indiana/Vincennes'
                  | 'America/Indiana/Winamac'
                  | 'America/Indianapolis'
                  | 'America/Inuvik'
                  | 'America/Iqaluit'
                  | 'America/Jamaica'
                  | 'America/Jujuy'
                  | 'America/Juneau'
                  | 'America/Kentucky/Monticello'
                  | 'America/Kralendijk'
                  | 'America/La_Paz'
                  | 'America/Lima'
                  | 'America/Los_Angeles'
                  | 'America/Louisville'
                  | 'America/Lower_Princes'
                  | 'America/Maceio'
                  | 'America/Managua'
                  | 'America/Manaus'
                  | 'America/Marigot'
                  | 'America/Martinique'
                  | 'America/Matamoros'
                  | 'America/Mazatlan'
                  | 'America/Mendoza'
                  | 'America/Menominee'
                  | 'America/Merida'
                  | 'America/Metlakatla'
                  | 'America/Mexico_City'
                  | 'America/Miquelon'
                  | 'America/Moncton'
                  | 'America/Monterrey'
                  | 'America/Montevideo'
                  | 'America/Montserrat'
                  | 'America/Nassau'
                  | 'America/New_York'
                  | 'America/Nome'
                  | 'America/Noronha'
                  | 'America/North_Dakota/Beulah'
                  | 'America/North_Dakota/Center'
                  | 'America/North_Dakota/New_Salem'
                  | 'America/Ojinaga'
                  | 'America/Panama'
                  | 'America/Paramaribo'
                  | 'America/Phoenix'
                  | 'America/Port-au-Prince'
                  | 'America/Port_of_Spain'
                  | 'America/Porto_Velho'
                  | 'America/Puerto_Rico'
                  | 'America/Punta_Arenas'
                  | 'America/Rankin_Inlet'
                  | 'America/Recife'
                  | 'America/Regina'
                  | 'America/Resolute'
                  | 'America/Rio_Branco'
                  | 'America/Santarem'
                  | 'America/Santiago'
                  | 'America/Santo_Domingo'
                  | 'America/Sao_Paulo'
                  | 'America/Scoresbysund'
                  | 'America/Sitka'
                  | 'America/St_Barthelemy'
                  | 'America/St_Johns'
                  | 'America/St_Kitts'
                  | 'America/St_Lucia'
                  | 'America/St_Thomas'
                  | 'America/St_Vincent'
                  | 'America/Swift_Current'
                  | 'America/Tegucigalpa'
                  | 'America/Thule'
                  | 'America/Tijuana'
                  | 'America/Toronto'
                  | 'America/Tortola'
                  | 'America/Vancouver'
                  | 'America/Whitehorse'
                  | 'America/Winnipeg'
                  | 'America/Yakutat'
                  | 'Antarctica/Casey'
                  | 'Antarctica/Davis'
                  | 'Antarctica/DumontDUrville'
                  | 'Antarctica/Macquarie'
                  | 'Antarctica/Mawson'
                  | 'Antarctica/McMurdo'
                  | 'Antarctica/Palmer'
                  | 'Antarctica/Rothera'
                  | 'Antarctica/Syowa'
                  | 'Antarctica/Troll'
                  | 'Antarctica/Vostok'
                  | 'Arctic/Longyearbyen'
                  | 'Asia/Aden'
                  | 'Asia/Almaty'
                  | 'Asia/Amman'
                  | 'Asia/Anadyr'
                  | 'Asia/Aqtau'
                  | 'Asia/Aqtobe'
                  | 'Asia/Ashgabat'
                  | 'Asia/Atyrau'
                  | 'Asia/Baghdad'
                  | 'Asia/Bahrain'
                  | 'Asia/Baku'
                  | 'Asia/Bangkok'
                  | 'Asia/Barnaul'
                  | 'Asia/Beirut'
                  | 'Asia/Bishkek'
                  | 'Asia/Brunei'
                  | 'Asia/Calcutta'
                  | 'Asia/Chita'
                  | 'Asia/Colombo'
                  | 'Asia/Damascus'
                  | 'Asia/Dhaka'
                  | 'Asia/Dili'
                  | 'Asia/Dubai'
                  | 'Asia/Dushanbe'
                  | 'Asia/Famagusta'
                  | 'Asia/Gaza'
                  | 'Asia/Hebron'
                  | 'Asia/Hong_Kong'
                  | 'Asia/Hovd'
                  | 'Asia/Irkutsk'
                  | 'Asia/Jakarta'
                  | 'Asia/Jayapura'
                  | 'Asia/Jerusalem'
                  | 'Asia/Kabul'
                  | 'Asia/Kamchatka'
                  | 'Asia/Karachi'
                  | 'Asia/Katmandu'
                  | 'Asia/Khandyga'
                  | 'Asia/Krasnoyarsk'
                  | 'Asia/Kuala_Lumpur'
                  | 'Asia/Kuching'
                  | 'Asia/Kuwait'
                  | 'Asia/Macau'
                  | 'Asia/Magadan'
                  | 'Asia/Makassar'
                  | 'Asia/Manila'
                  | 'Asia/Muscat'
                  | 'Asia/Nicosia'
                  | 'Asia/Novokuznetsk'
                  | 'Asia/Novosibirsk'
                  | 'Asia/Omsk'
                  | 'Asia/Oral'
                  | 'Asia/Phnom_Penh'
                  | 'Asia/Pontianak'
                  | 'Asia/Pyongyang'
                  | 'Asia/Qatar'
                  | 'Asia/Qostanay'
                  | 'Asia/Qyzylorda'
                  | 'Asia/Rangoon'
                  | 'Asia/Riyadh'
                  | 'Asia/Saigon'
                  | 'Asia/Sakhalin'
                  | 'Asia/Samarkand'
                  | 'Asia/Seoul'
                  | 'Asia/Shanghai'
                  | 'Asia/Singapore'
                  | 'Asia/Srednekolymsk'
                  | 'Asia/Taipei'
                  | 'Asia/Tashkent'
                  | 'Asia/Tbilisi'
                  | 'Asia/Tehran'
                  | 'Asia/Thimphu'
                  | 'Asia/Tokyo'
                  | 'Asia/Tomsk'
                  | 'Asia/Ulaanbaatar'
                  | 'Asia/Urumqi'
                  | 'Asia/Ust-Nera'
                  | 'Asia/Vientiane'
                  | 'Asia/Vladivostok'
                  | 'Asia/Yakutsk'
                  | 'Asia/Yekaterinburg'
                  | 'Asia/Yerevan'
                  | 'Atlantic/Azores'
                  | 'Atlantic/Bermuda'
                  | 'Atlantic/Canary'
                  | 'Atlantic/Cape_Verde'
                  | 'Atlantic/Faeroe'
                  | 'Atlantic/Madeira'
                  | 'Atlantic/Reykjavik'
                  | 'Atlantic/South_Georgia'
                  | 'Atlantic/St_Helena'
                  | 'Atlantic/Stanley'
                  | 'Australia/Adelaide'
                  | 'Australia/Brisbane'
                  | 'Australia/Broken_Hill'
                  | 'Australia/Darwin'
                  | 'Australia/Eucla'
                  | 'Australia/Hobart'
                  | 'Australia/Lindeman'
                  | 'Australia/Lord_Howe'
                  | 'Australia/Melbourne'
                  | 'Australia/Perth'
                  | 'Australia/Sydney'
                  | 'Europe/Amsterdam'
                  | 'Europe/Andorra'
                  | 'Europe/Astrakhan'
                  | 'Europe/Athens'
                  | 'Europe/Belgrade'
                  | 'Europe/Berlin'
                  | 'Europe/Bratislava'
                  | 'Europe/Brussels'
                  | 'Europe/Bucharest'
                  | 'Europe/Budapest'
                  | 'Europe/Busingen'
                  | 'Europe/Chisinau'
                  | 'Europe/Copenhagen'
                  | 'Europe/Dublin'
                  | 'Europe/Gibraltar'
                  | 'Europe/Guernsey'
                  | 'Europe/Helsinki'
                  | 'Europe/Isle_of_Man'
                  | 'Europe/Istanbul'
                  | 'Europe/Jersey'
                  | 'Europe/Kaliningrad'
                  | 'Europe/Kiev'
                  | 'Europe/Kirov'
                  | 'Europe/Lisbon'
                  | 'Europe/Ljubljana'
                  | 'Europe/London'
                  | 'Europe/Luxembourg'
                  | 'Europe/Madrid'
                  | 'Europe/Malta'
                  | 'Europe/Mariehamn'
                  | 'Europe/Minsk'
                  | 'Europe/Monaco'
                  | 'Europe/Moscow'
                  | 'Europe/Oslo'
                  | 'Europe/Paris'
                  | 'Europe/Podgorica'
                  | 'Europe/Prague'
                  | 'Europe/Riga'
                  | 'Europe/Rome'
                  | 'Europe/Samara'
                  | 'Europe/San_Marino'
                  | 'Europe/Sarajevo'
                  | 'Europe/Saratov'
                  | 'Europe/Simferopol'
                  | 'Europe/Skopje'
                  | 'Europe/Sofia'
                  | 'Europe/Stockholm'
                  | 'Europe/Tallinn'
                  | 'Europe/Tirane'
                  | 'Europe/Ulyanovsk'
                  | 'Europe/Vaduz'
                  | 'Europe/Vatican'
                  | 'Europe/Vienna'
                  | 'Europe/Vilnius'
                  | 'Europe/Volgograd'
                  | 'Europe/Warsaw'
                  | 'Europe/Zagreb'
                  | 'Europe/Zurich'
                  | 'Indian/Antananarivo'
                  | 'Indian/Chagos'
                  | 'Indian/Christmas'
                  | 'Indian/Cocos'
                  | 'Indian/Comoro'
                  | 'Indian/Kerguelen'
                  | 'Indian/Mahe'
                  | 'Indian/Maldives'
                  | 'Indian/Mauritius'
                  | 'Indian/Mayotte'
                  | 'Indian/Reunion'
                  | 'Pacific/Apia'
                  | 'Pacific/Auckland'
                  | 'Pacific/Bougainville'
                  | 'Pacific/Chatham'
                  | 'Pacific/Easter'
                  | 'Pacific/Efate'
                  | 'Pacific/Enderbury'
                  | 'Pacific/Fakaofo'
                  | 'Pacific/Fiji'
                  | 'Pacific/Funafuti'
                  | 'Pacific/Galapagos'
                  | 'Pacific/Gambier'
                  | 'Pacific/Guadalcanal'
                  | 'Pacific/Guam'
                  | 'Pacific/Honolulu'
                  | 'Pacific/Kiritimati'
                  | 'Pacific/Kosrae'
                  | 'Pacific/Kwajalein'
                  | 'Pacific/Majuro'
                  | 'Pacific/Marquesas'
                  | 'Pacific/Midway'
                  | 'Pacific/Nauru'
                  | 'Pacific/Niue'
                  | 'Pacific/Norfolk'
                  | 'Pacific/Noumea'
                  | 'Pacific/Pago_Pago'
                  | 'Pacific/Palau'
                  | 'Pacific/Pitcairn'
                  | 'Pacific/Ponape'
                  | 'Pacific/Port_Moresby'
                  | 'Pacific/Rarotonga'
                  | 'Pacific/Saipan'
                  | 'Pacific/Tahiti'
                  | 'Pacific/Tarawa'
                  | 'Pacific/Tongatapu'
                  | 'Pacific/Truk'
                  | 'Pacific/Wake'
                  | 'Pacific/Wallis'
                )
              | null;
            /**
             * When disabled, submissions use the default timezone only.
             */
            includeTimezoneSelect?: boolean | null;
            /**
             * Optional. Format: YYYY-MM-DDTHH:mm:ss[IANA/Timezone]
             */
            defaultValue?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'datetime';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  client?: T;
  excerpt?: T;
  images?:
    | T
    | {
        image?: T;
        isFeatured?: T;
        id?: T;
      };
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        datetime?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultTimezone?: T;
              includeTimezoneSelect?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteTagline?: string | null;
  /**
   * Label for the header button that opens the discovery call form modal.
   */
  primaryCtaLabel?: string | null;
  /**
   * Form opened in a modal when visitors click the primary header CTA.
   */
  discoveryCallForm?: (number | null) | Form;
  /**
   * Short text shown under the modal title before the form is submitted.
   */
  discoveryCallModalDescription?: string | null;
  socialLinks?: {
    instagram?: string | null;
    linkedin?: string | null;
    email?: string | null;
  };
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  /**
   * First part of the headline (sans-serif)
   */
  headline: string;
  /**
   * Rendered in serif italic
   */
  headlineAccent: string;
  subheadline: string;
  /**
   * Full-width background image. Subject centered or right works best.
   */
  heroImage?: (number | null) | Media;
  heroCta: {
    type?: ('reference' | 'custom') | null;
    newTab?: boolean | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    url?: string | null;
    label: string;
  };
  taglineLead?: string | null;
  /**
   * Rendered in serif italic
   */
  taglineAccent?: string | null;
  outputs: {
    overline?: string | null;
    headline: string;
    body?: string | null;
    cta: {
      type?: ('reference' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'projects';
            value: number | Project;
          } | null);
      url?: string | null;
      label: string;
    };
    cards?:
      | {
          /**
           * e.g. Ecommerce, Campaign, Social Content
           */
          label: string;
          /**
           * Optional until media is uploaded in admin or via seed.
           */
          image?: (number | null) | Media;
          isVideo?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  impact?: {
    overline?: string | null;
    stats?:
      | {
          icon: 'clock' | 'cube' | 'image' | 'document';
          /**
           * Large display line, e.g. "30–40%" or "Reduced"
           */
          headline: string;
          subheading: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Small label above the headline.
   */
  overline?: string | null;
  headline: string;
  bio: string;
  portrait?: (number | null) | Media;
  credentials?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  sidebarItems?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page".
 */
export interface ProjectsPage {
  id: number;
  /**
   * Small label above the headline.
   */
  overline?: string | null;
  headline: string;
  /**
   * Optional supporting copy below the headline.
   */
  intro?: string | null;
  /**
   * Shown when no published projects are available.
   */
  emptyStateMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'projects';
                value: number | Project;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteTagline?: T;
  primaryCtaLabel?: T;
  discoveryCallForm?: T;
  discoveryCallModalDescription?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        email?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  headline?: T;
  headlineAccent?: T;
  subheadline?: T;
  heroImage?: T;
  heroCta?:
    | T
    | {
        type?: T;
        newTab?: T;
        reference?: T;
        url?: T;
        label?: T;
      };
  taglineLead?: T;
  taglineAccent?: T;
  outputs?:
    | T
    | {
        overline?: T;
        headline?: T;
        body?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        cards?:
          | T
          | {
              label?: T;
              image?: T;
              isVideo?: T;
              id?: T;
            };
      };
  impact?:
    | T
    | {
        overline?: T;
        stats?:
          | T
          | {
              icon?: T;
              headline?: T;
              subheading?: T;
              description?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  overline?: T;
  headline?: T;
  bio?: T;
  portrait?: T;
  credentials?:
    | T
    | {
        label?: T;
        id?: T;
      };
  sidebarItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects-page_select".
 */
export interface ProjectsPageSelect<T extends boolean = true> {
  overline?: T;
  headline?: T;
  intro?: T;
  emptyStateMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}